// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytefabwphcnzkttqihlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZWZhYndwaGNuemt0dHFpaGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTEzNDYsImV4cCI6MjA1OTk2NzM0Nn0.R5t8FB53AgnjUvpZQy_hUo7HJ_O7EsAq31bmGmE8C1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);